### ISSUE TITLE
The function parameter [Route] has reflective XSS

### ISSUE THREAD

**Issue by Stellarsss** [xujinliang/zibbs#4]
First follow to the index.php entry file, which will load the frame file directly, so just visit the following address
`http://20.20.20.130:8000/zibbs/index.php`
`http://20.20.20.130:8000/zibbs`
Will directly load the framework file and instantiate the framework class
![图片](https://user-images.githubusercontent.com/33337704/84992814-fb644380-b17a-11ea-8d72-6bb437d2dc13.png)
Directly trace to the **core/framework.php** file. After analysis, this CMS handles the processing of each controller and operation through 【route】, wherein the parameter route is the controller name and action name to be filled in in this GET request.
**core/framework.php**
![图片](https://user-images.githubusercontent.com/33337704/84992835-04551500-b17b-11ea-9c12-aa05f81e02d4.png)
A normal GET request would look like this
http://20.20.20.130:8000/zibbs/index.php?route=admin/login
![图片](https://user-images.githubusercontent.com/33337704/84992855-0b7c2300-b17b-11ea-9ba2-89df40f273cb.png)
And here the parameter 【route】 is controllable, The value of the input parameter 【route】 is processed as follows, The value of the parameter【router】is first split through /，Such as route=aaa/bbb, the aaa Is the controller name,bbb for the action of, It also makes conditional judgments about whether the controller and the action name exist, When the Controller name does not exist, it will directly output "aaa Controller Controller does not exist 11111", as shown below
![图片](https://user-images.githubusercontent.com/33337704/84992877-15058b00-b17b-11ea-9ef9-86124271d9c9.png)
![图片](https://user-images.githubusercontent.com/33337704/84992891-1a62d580-b17b-11ea-8bfa-33a03ba10d33.png)
This is for the parameter 【route】, If the controller doesn't exist, The value of the input parameter 【route】 is displayed directly, And the following values, without XSS filtering, Only the addslashes() method is done here, and there is no XSS filtering function in this aspect
![图片](https://user-images.githubusercontent.com/33337704/84992914-22bb1080-b17b-11ea-8d96-2471522cfffe.png)
Because there is no filtering here, there is reflective XSS, which is tested as follows
Because of the split for / here, the regular XSS payload cannot be taken from a bomb frame, so using the following XSS payload can make a bomb fram
<img src=x onerror=prompt(1)>
http://20.20.20.130:8000/zibbs/index.php?route=1111%3Cimg%20src=x%20onerror=prompt(1)%3E
![图片](https://user-images.githubusercontent.com/33337704/84992939-2d75a580-b17b-11ea-8d5d-ff7da9d85105.png)
![图片](https://user-images.githubusercontent.com/33337704/84992990-36ff0d80-b17b-11ea-8d6b-c415a049f421.png)
The following test statement can also cause a pop-up as normal
route=admin/<img src=x onerror=prompt(1)>

![图片](https://user-images.githubusercontent.com/33337704/84993014-41b9a280-b17b-11ea-93e8-d850888b600a.png)
**Solution：**
filter or encode special characters like this
<
>
"
'
&
%
... ...
and filter some keyword like this

script
javascript

... ...
or filter some label function which can run javascript like this
onclick
onerror
onload
... ...

**Comment by xujinliang** [comment]
3Q ，you are a good man
